trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - develop
    - release*
  paths:
    exclude:
    - README.md

pr: none

variables:
  repository: 'focal-freedom-236620/core-networking'
  build: $(Build.BuildId)
  ref: $(Build.SourceBranch)
  branch: $(Build.SourceBranchName)
  version:

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      . version
      VERS=$MAJOR.$MINOR.$PATCH$SUFFIX
      if [[ $(ref) == refs/tags* ]]; then
        TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
        if [[ $TAG != $VERS ]]; then
          echo 'Version file does not match git tag'
          exit 1
        fi
      fi
      echo "##vso[task.setvariable variable=version]$VERS"
    displayName: 'Set version variable'

  - task: Docker@2
    displayName: 'docker build and push'
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: $(repository)
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        $(version)
        $(branch)
        $(branch)-$(build)
        latest

  - script: |
      echo $(version) > $(Build.ArtifactStagingDirectory)/version.txt
    displayName: 'Create version artefact'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'core-networking'
    displayName: 'Publish artefacts'